---
name: ci pipeline python application
on:
  push:
    branches: main
jobs:
  dev:
    runs-on: ubuntu-latest
  steps:
    - name: checkout code
      used: actions/checkout@v4
    - name: setup python
      uses: actions/ setup-python@v5
      with:
        python-version: "3.11"
    - name: run code
      run: python app1.py
         
